//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHouse.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentAddresses
    {
        public int IDApartAddres { get; set; }
        public int IDFlat { get; set; }
        public int IDAddresses { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Flat Flat { get; set; }
    }
}
