//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHouse.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int IDHistory { get; set; }
        public int IDDevice { get; set; }
        public bool ConditionOld { get; set; }
        public bool ConditionNew { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
