//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHouse.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeDop
    {
        public int IDUsers { get; set; }
        public Nullable<int> IDRooms { get; set; }
        public string NameRoom { get; set; }
        public string FlatName { get; set; }
        public int IDFlat { get; set; }
    }
}
