//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHouse.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OurControllers
    {
        public int IDOurControllers { get; set; }
        public int IDRoom { get; set; }
        public int IDDevice { get; set; }
        public bool Condition { get; set; }
        public int PowerConsumption { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
