//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHouse.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScenariosView
    {
        public int IDUsers { get; set; }
        public int IDOurControllers { get; set; }
        public System.TimeSpan Time { get; set; }
        public bool Action { get; set; }
        public int DayWeek { get; set; }
        public string Title { get; set; }
    }
}
