//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHouse.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scenarios
    {
        public int IDScenarios { get; set; }
        public int IDDevice { get; set; }
        public System.TimeSpan Time { get; set; }
        public bool Action { get; set; }
        public int DayWeek { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
