//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHouse.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SHEntities : DbContext
    {
        public SHEntities()
            : base("name=SHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<ApartmentAddress> ApartmentAddress { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<Flat> Flat { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<OurControllers> OurControllers { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeConnection> TypeConnection { get; set; }
        public virtual DbSet<UserLogins> UserLogins { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Home> Home { get; set; }
        public virtual DbSet<HomeDop> HomeDop { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<userView> userView { get; set; }
    }
}
